name: first-workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo "First Workflow"
      - name: print goodbye
        run: echo "GoodBye!"
